### ISSUE TITLE
JS widget

### ISSUE THREAD

**Issue by whatabeautifulname** [spinitron/v2-web-integration#4]
This is what I'm getting
![whatiget](https://user-images.githubusercontent.com/44352066/54078186-e5c65580-4278-11e9-8ed8-d1eb70c341f4.PNG)

This is from the spinitron website and I want to be getting.
![whatiwant](https://user-images.githubusercontent.com/44352066/54078188-e6f78280-4278-11e9-974f-8e6fe100325c.PNG)

**Comment by spinitron** [comment]
Check the console in your browser's development tools. It might tell you what's wrong.

Are you running a real web server? If you're opening a file in the browser then it can't load any other resources linked from the page from the network.

Why not fork this repo in Github, modify it as you please, and use Github Pages as the web server?

**Comment by Plastic46c** [comment]
I think that solved it, open in browser is not actually duct tape.
Thanks so much!!
